[build]
    publish = "portafolio/src" # La carpeta donde est치 tu index.html
    command = "" # No necesitas comando de construcci칩n para un sitio est치tico

[dev]
    framework = "static" # Indica que es un sitio est치tico

[functions]
    directory = "netlify/functions" # Carpeta para funciones serverless (opcional)
